# Generated by Django 3.2.3 on 2021-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50, verbose_name='название товара')),
                ('product_text', models.TextField(verbose_name='описание товара')),
                ('product_price', models.IntegerField(verbose_name='цена товара')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('review_text', models.CharField(max_length=200, verbose_name='текст отзыва')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
